import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: " Welcome Next.js App", // default title for each page
    template: "%s | Next.js App",//  template for each page
  },
  description: "Generated by create next app",
};

// Active Navigation links
const navigation=[
  { name: 'About', href: '/About' },
  { name: 'Contact', href: '/contact' },
  { name: 'Chart', href: '/chart' },
  { name: 'Line Chart', href: '/chart/line-chart' },
  { name: 'Blog', href: '/blog' },
  { name: 'My Folder', href: '/myfolder' },
  { name: 'Product', href: '/product' }
]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex gap-4 p-4 bg-gray-200 dark:bg-gray-800 text-gray-800 dark:text-gray-200 hover:geist_a71539c9-module__T19VSG__className">
          <Link href='/About'>About</Link>
          <Link href='/contact'>Contact</Link>
          <Link href='/chart'>Chart</Link>
          <Link href='/chart/line-chart'>Line Chart</Link>
          <Link href='/blog'>blog Page</Link>
          <Link href='/myfolder'>My Folder</Link>
          <Link href='/product'>Product</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
